app:
  fullName: GPS TrackUI
  instance: default
database:
  host: data.ge.rgunti.ch
  port: 3306
  dbName: carpi-rec
  username: carpi-rec
  password: carpi-rec
server:
  port: 2030
  showTraces: true
  enableDebugRoutes: true
logging:
  logBase: 'GPSTrackUI'
  logToStdout: 'debug,info,warn'
  showTimestamp: true
  timestampFormat: 'Y-MM-DD HH:mm:ss.SSS'
internals:
  dirs:
    views: /views
    hbs:
      partials: /views/partials
      layouts: /views/layouts
      defaultLayout: /views/layouts/main.hbs
    routes: /config/routes.json
    staticRoutes: /config/static-routes.json
